# Generated by Django 4.2.1 on 2023-05-21 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dietas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Platillos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('caloriasPorPorcion', models.FloatField()),
                ('proteinasPorPorcion', models.FloatField()),
                ('carbohidratosPorPorcion', models.FloatField()),
                ('grasasPorPorcion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('genero', models.CharField(max_length=255)),
                ('nivelActividad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendacion', models.TextField()),
                ('id_dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri.dietas')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='DietasPlatillos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comida', models.CharField(max_length=255)),
                ('id_dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri.dietas')),
                ('id_platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri.platillos')),
            ],
        ),
    ]
